### ISSUE TITLE
line associations in remote destination

### ISSUE THREAD

**Issue by Sivolen** [CiscoDevNet/axl-python-zeep-samples#11]
Hi, help me please, how add line in remote destination? 
I add parameter lineAssociations: "1" but is not work

My dict

remote_destination = {

"name": "Gridnev.A.A._RDI",
"destination": "mynumber",
"ownerUserId": "a.gridnev",
"enableUnifiedMobility": "true",
"enableMobileConnect": "true",
"isMobilePhone": "true",
"remoteDestinationProfileName": "Gridnev.A.A._RDPI",
"lineAssociations": "1"
}

**Comment by dstaudt** [comment]
Looks like the <lineAssociations> list needs to identify line associations by either UIID or pattern/partition - the entry of just '1' doesn't make sense - perhaps this is the 1st line in the RDP?
![Screenshot-20211108125235-650x224](https://user-images.githubusercontent.com/2250445/140801668-772d3aea-6031-4dfd-8286-555e5b806029.png)
So something like:
```python
...
"lineAssociations": {
    "lineAssociation": [
        {
            "pattern": "1000",
            "routePartitionName": None
        }
    ]
}
...

**Comment by Sivolen** [comment]
Hi, i change my dict 

```
remote_destination = {

"name": "Gridnev.A.A._RDI",
"destination": "mynamber",
"ownerUserId": "a.gridnev",
"enableUnifiedMobility": "true",
"enableMobileConnect": "true",
"isMobilePhone": "true",
"remoteDestinationProfileName": "Gridnev.A.A._RDPI",
"lineAssociations": {
    "lineAssociation": [
        {
            "pattern": "11111",
            "routePartitionName": None
        }
    ]
}
}
```

and i tried run script but remote destination not created.
i change my dict again,  add  "routePartitionName": "Internal",


remote_destination = {

    "name": "SOCI_Gridnev.A.A._RDI",
    "destination": "89147599008",
    "ownerUserId": "a.gridnev",
    "enableUnifiedMobility": "true",
    "enableMobileConnect": "true",
    "isMobilePhone": "true",
    "remoteDestinationProfileName": "SOCI_Gridnev.A.A._RDPI",
    "lineAssociations": {
        "lineAssociation": [
            {
                "pattern": "12169",
                "routePartitionName": "Internal",
            }
        ]
    }
}

Its work correct 
thanks

**Comment by Sivolen** [comment]
I did it, change dict 

```

    'lines': {
        'line': {'index': '1', 'dirn':
            {'pattern': '12169',
             "routePartitionName": "Internal",
             },
                 "recordingMediaSource": "Gateway Preferred",

                 },
        'display': 'Гриднев А.А.',
```

he need "index"
