### ISSUE TITLE
getphone - Response convert to JSON

### ISSUE THREAD

**Issue by sanzcarlos** [CiscoDevNet/axl-python-zeep-samples#4]
Hello:

I have made a function that uses the AXL getphone method to get all the parameters of a phone, I use the function:

`json.loads(json.dumps(zeep.helpers.serialize_object(Response['return']))`

To convert the output that zeeps back to a JSON, this works for the addphone, removephone methods, but it doesn't work for the getphone method, because I get the following error:

`TypeError: Object of type _Element is not JSON serializable`

Do you know any way to solve this problem I have?. Thanks

Regards,
Carlos Sanz

**Comment by sanzcarlos** [comment]
Hello:

I found the issue I had, the addphone function returns the vendorConfig parameter which is a list and not a dictionary, I had to convert that value to dictionary in order to return a JSON in my function. Thank you.

Regards,
Carlos Sanz

**Comment by simstems** [comment]
> Hello:
> 
> I found the issue I had, the addphone function returns the vendorConfig parameter which is a list and not a dictionary, I had to convert that value to dictionary in order to return a JSON in my function. Thank you.
> 
> Regards, Carlos Sanz

How did you convert the value to a dictionary? I keep getting this:

{'return': None, 'sequence': None}
