### ISSUE TITLE
os.getenv( 'USERNAME' )

### ISSUE THREAD

**Issue by kevsm** [CiscoDevNet/axl-python-zeep-samples#6]
Has anyone experienced issues with the windows OS returning their desktop account for os.getenv( 'USERNAME' )?
This could just be an isolated issue with me or a failure to install python correctly, but had to change the .env file to leverage something other than USERNAME (like userID) to prevent my windows username from being used.

![env_file](https://user-images.githubusercontent.com/78400056/106554767-a4309a80-64e1-11eb-8ac8-f63d506f9502.png)

**Comment by dstaudt** [comment]
Good catch...should be more careful in general about environment variable collisions.  Made a change to AXL_USERNAME and AXL_PASSWORD to address in all samples
